
baseurl = "https://dzyla.github.io/Follow_Relion_gracefully/"
title = "Follow Relion Gracefully"
languageCode = "en-us"

# Pagination
paginate = 10
paginatePath = "page"

# Copyright
copyright = "2021 / Follow Relion Gracefully / Dawid Zyla"

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header

  # Footer
  [[menu.footer]]
    url = "https://github.com/dzyla/Follow_Relion_gracefully"
    name = "GitHub"
    weight = 1

  [[menu.footer]]
    url = "mailto:dzyla@lji.org"
    name = "Contact"
    weight = 2


# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  datefmt  = "Jan 2, 2006"
  plotly= true
    
