name: FollowRelion
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy<2.0
  - pandas
  - mrcfile
  - scikit-image
  - scipy
  - matplotlib
  - seaborn
  - pillow
  - plotly
  - streamlit
  - pyvis
  - gemmi
  - altair
  - pip:
      - stqdm
      - PyMCubes
      - morphosamplers
      - streamlit-bokeh
      - streamlit-bokeh-events
