# Constants for RELION Column Names
RLN_PROCESS_TYPE_LABEL = "_rlnPipeLineProcessTypeLabel"
RLN_PROCESS_ALIAS = "_rlnPipeLineProcessAlias"
RLN_PROCESS_NAME = "_rlnPipeLineProcessName"
RLN_STATUS_LABEL = "_rlnPipeLineProcessStatusLabel"

RLN_MICROGRAPH_NAME = "_rlnMicrographName"
RLN_DEFOCUS_U = "_rlnDefocusU"
RLN_DEFOCUS_V = "_rlnDefocusV"
RLN_DEFOCUS_ANGLE = "_rlnDefocusAngle"
RLN_PHASE_SHIFT = "_rlnPhaseShift"
RLN_CTF_MAX_RESOLUTION = "_rlnCtfMaxResolution"
RLN_CTF_FIGURE_OF_MERIT = "_rlnCtfFigureOfMerit"
RLN_VOLTAGE = "_rlnVoltage"
RLN_SPHERICAL_ABERRATION = "_rlnSphericalAberration"
RLN_AMPLITUDE_CONTRAST = "_rlnAmplitudeContrast"
RLN_MAGNIFICATION = "_rlnMagnification"
RLN_DETECTOR_PIXEL_SIZE = "_rlnDetectorPixelSize"
RLN_BEAM_TILT_X = "_rlnBeamTiltX"
RLN_BEAM_TILT_Y = "_rlnBeamTiltY"

RLN_COORDINATE_X = "_rlnCoordinateX"
RLN_COORDINATE_Y = "_rlnCoordinateY"
RLN_COORDINATE_Z = "_rlnCoordinateZ"
RLN_CENTERED_COORDINATE_X_ANGST = "_rlnCenteredCoordinateXAngst"
RLN_CENTERED_COORDINATE_Y_ANGST = "_rlnCenteredCoordinateYAngst"
RLN_CENTERED_COORDINATE_Z_ANGST = "_rlnCenteredCoordinateZAngst"
RLN_AUTOPICK_FOM = "_rlnAutopickFigureOfMerit"
RLN_CLASS_NUMBER = "_rlnClassNumber"
RLN_ANGLE_ROT = "_rlnAngleRot"
RLN_ANGLE_TILT = "_rlnAngleTilt"
RLN_ANGLE_PSI = "_rlnAnglePsi"
RLN_ORIGIN_X_ANGST = "_rlnOriginXAngst"
RLN_ORIGIN_Y_ANGST = "_rlnOriginYAngst"
RLN_TOMO_NAME = "_rlnTomoName"

RLN_REFERENCE_IMAGE = "_rlnReferenceImage"
RLN_CLASS_DISTRIBUTION = "_rlnClassDistribution"
RLN_ESTIMATED_RESOLUTION = "_rlnEstimatedResolution"
RLN_GOLD_STANDARD_FSC = "_rlnGoldStandardFsc"
RLN_ANGSTROM_RESOLUTION = "_rlnAngstromResolution"

RLN_PIPELINE_EDGE_FROM_NODE = "_rlnPipeLineEdgeFromNode"
RLN_PIPELINE_EDGE_PROCESS = "_rlnPipeLineEdgeProcess"
RLN_PIPELINE_NODE_NAME = "_rlnPipeLineNodeName"

# Constants for STAR File Keys
PIPELINE_PROCESSES_KEY = "pipeline_processes"
PIPELINE_NODES_KEY = "pipeline_nodes"
PIPELINE_EDGES_KEY = "pipeline_input_edges"

# Constants for Special Processes
FLOWCHART_PROCESS = "relion.flowchart"
INTERACTIVE_PLOT_PROCESS = "relion.InteractivePlot"

# Constants for Session State Keys
STATE_SELECTED_PROCESS = "selected_process"
STATE_CURRENT_JOB = "current_job"
STATE_JOB_PARAMS = "job_params"
STATE_PROCESS_RADIO_KEY = "process_radio_key"
STATE_JOB_RADIO_KEY = "job_radio_key"
STATE_PASSWORD_ARGS = "password_args"
STATE_DEFAULT_FOLDER = "default_job_folder"
STATE_CURRENT_FOLDER = "current_folder_path"
STATE_DISPLAY_TO_ORIGINAL_PROCESS = "display_to_original_process_map"
STATE_JOBS_DICT = "jobs_dict"
TEMP_DIR_PATH = "temp"

# Key Prefixes (for dynamic state)
PREFIX_SELECTED_INDICES = "selected_indices_"
PREFIX_LOADED_CLASSES = "loaded_classes_"
PREFIX_DOWNLOAD_INFO = "download_info_"
PREFIX_SHOW_DOWNLOAD = "show_download_"
PREFIX_SHOW_SELECTED_AREA = "show_selected_area_"
